import { shortHash } from "@/lib/events/hash";
import { PHASE_LABELS } from "@/lib/events/types";
import { formatDuration, formatUtc } from "@/lib/utils";
import type { ReportModel } from "./build";

/**
 * Markdown rendering of the incident report.
 *
 * Every report is produced in both Markdown and PDF. The PDF is what gets
 * emailed to a moderator; the Markdown is what a student pastes into a
 * portfolio, a lecturer diffs between two attempts, and a marking script can
 * actually parse. Producing only a PDF would make the assessment data
 * effectively write-only.
 */

function table(headers: string[], rows: string[][]): string {
  if (rows.length === 0) return "_None recorded._\n";
  const escape = (cell: string) => cell.replace(/\|/g, "\\|").replace(/\n+/g, " ");
  return [
    `| ${headers.join(" | ")} |`,
    `| ${headers.map(() => "---").join(" | ")} |`,
    ...rows.map((row) => `| ${row.map(escape).join(" | ")} |`),
  ].join("\n");
}

export function renderReportMarkdown(model: ReportModel): string {
  const g = model.grade;
  const out: string[] = [];

  out.push(`# Incident Report: ${model.scenario.title}`);
  out.push("");
  out.push(
    "> Generated by NocturneAnalysis from a training exercise. **All data in this report is " +
      "synthetic** - no real systems, networks or people are involved.",
  );
  out.push("");

  // ------------------------------------------------------------- header --
  out.push("## Report details");
  out.push("");
  out.push(
    table(
      ["Field", "Value"],
      [
        ["Analyst", model.analyst_handle],
        ["Organisation", model.organization_name],
        ["Scenario", `${model.scenario.title} (${model.scenario.difficulty})`],
        ["Category", model.scenario.category],
        ["Affected entity", model.scenario.organization],
        ["Session started", formatUtc(model.started_at ?? "")],
        ["Session completed", model.completed_at ? formatUtc(model.completed_at) : "In progress"],
        ["Time on incident", formatDuration(model.duration_ms)],
        [
          "Time to containment",
          model.time_to_contain_ms === null ? "Not contained" : formatDuration(model.time_to_contain_ms),
        ],
        ["Report generated", formatUtc(model.generated_at)],
        ["Session reference", model.session_id],
      ],
    ),
  );
  out.push("");

  // ---------------------------------------------------------- integrity --
  out.push("## Evidence integrity");
  out.push("");
  if (model.integrity.valid) {
    out.push(
      `All ${model.integrity.length} recorded events form an unbroken SHA-256 hash chain. Each ` +
        `event's digest covers the previous event's digest, its own payload, its server-assigned ` +
        `timestamp and its type, so any insertion, deletion, reordering or edit would break the ` +
        `chain at that point.`,
    );
    out.push("");
    out.push(`- **Chain head:** \`${model.integrity.headHash}\``);
    out.push(`- **Events recorded:** ${model.event_count}`);
    out.push(`- **Verification:** PASS`);
  } else {
    out.push(
      `**This session's audit log did not verify.** ${model.integrity.reason ?? ""} ` +
        `The failure is at event ${(model.integrity.brokenAtIndex ?? 0) + 1}. Treat the findings ` +
        `below as unconfirmed until the cause is established.`,
    );
    out.push("");
    out.push(`- **Verification:** FAIL`);
  }
  out.push("");

  // ---------------------------------------------------- executive summary --
  out.push("## Executive summary");
  out.push("");
  out.push(model.executive_summary);
  out.push("");

  // ---------------------------------------------------------- root cause --
  out.push("## Root cause");
  out.push("");
  out.push(model.scenario.root_cause);
  out.push("");

  // ------------------------------------------------------------ timeline --
  out.push("## Timeline of analyst actions");
  out.push("");
  out.push(
    "Reconstructed by replaying the session's event log in order. Navigation events (opening " +
      "alerts, reading individual log lines) are omitted here and present in the full export.",
  );
  out.push("");
  out.push(
    table(
      ["Time (UTC)", "Phase", "Action", "Detail"],
      model.timeline.map((row) => [
        formatUtc(row.at),
        row.phase ? PHASE_LABELS[row.phase] : "-",
        row.action,
        row.detail,
      ]),
    ),
  );
  out.push("");

  out.push("### Time spent per phase");
  out.push("");
  out.push(
    table(
      ["Phase", "Duration"],
      model.phase_durations.map((p) => [
        p.label,
        p.duration_ms === null ? "Not reached" : formatDuration(p.duration_ms),
      ]),
    ),
  );
  out.push("");

  // ---------------------------------------------------------------- IOCs --
  out.push("## Indicators of compromise");
  out.push("");
  out.push(
    table(
      ["Indicator", "Type", "Status", "Notes"],
      model.iocs.map((ioc) => [
        `\`${ioc.value}\``,
        ioc.ioc_type,
        ioc.status === "correct"
          ? "Identified"
          : ioc.status === "missed"
            ? "Missed"
            : "False positive",
        ioc.description,
      ]),
    ),
  );
  out.push("");

  // -------------------------------------------------------------- MITRE --
  out.push("## MITRE ATT&CK coverage");
  out.push("");
  out.push(
    table(
      ["Technique", "Name", "Tactic", "Identified"],
      model.techniques.map((t) => [`\`${t.id}\``, t.name, t.tactic, t.matched ? "Yes" : "No"]),
    ),
  );
  if (model.technique_false_positives.length > 0) {
    out.push("");
    out.push(
      `**Techniques claimed without supporting evidence:** ${model.technique_false_positives
        .map((t) => `\`${t}\``)
        .join(", ")}`,
    );
  }
  out.push("");

  // -------------------------------------------------------------- OWASP --
  if (model.owasp.length > 0) {
    out.push("## OWASP Top 10 (2021) mapping");
    out.push("");
    out.push(
      table(
        ["Category", "In plain language"],
        model.owasp.map((c) => [`**${c.name}**`, c.plain_language]),
      ),
    );
    out.push("");
  }

  // ------------------------------------------------------- per-phase work --
  out.push("## Decisions recorded");
  out.push("");
  for (const phase of ["triage", "investigation", "containment", "eradication", "recovery", "lessons_learned"] as const) {
    const decisions = g.decisions.filter((d) => d.phase === phase);
    if (decisions.length === 0) continue;

    out.push(`### ${PHASE_LABELS[phase]}`);
    out.push("");
    for (const decision of decisions) {
      const verdict =
        decision.correct === null ? "Not machine-graded" : decision.correct ? "Correct" : "Incorrect";
      out.push(`**${decision.prompt}**`);
      out.push("");
      out.push(`- Answered: ${decision.given_labels.join("; ") || "_Not answered_"}`);
      if (decision.expected_labels.length > 0) {
        out.push(`- Expected: ${decision.expected_labels.join("; ")}`);
      }
      out.push(`- Result: ${verdict} (${decision.points_earned}/${decision.points_possible} points)`);
      if (decision.student_rationale) {
        out.push(`- Analyst's reasoning: ${decision.student_rationale}`);
      }
      out.push("");
    }

    const actions = g.actions.filter((a) => a.phase === phase && a.taken);
    if (actions.length > 0) {
      out.push(
        table(
          ["Action taken", "Target", "Appropriate", "Points"],
          actions.map((a) => [a.label, a.target, a.is_correct ? "Yes" : "No", String(a.points_earned)]),
        ),
      );
      out.push("");
    }
  }

  // ---------------------------------------------------------- reflection --
  out.push("## Lessons learned");
  out.push("");
  if (model.reflection) {
    out.push("### What happened");
    out.push("");
    out.push(model.reflection.what_happened || "_Not completed._");
    out.push("");
    out.push("### What worked");
    out.push("");
    out.push(model.reflection.what_worked || "_Not completed._");
    out.push("");
    out.push("### What should change");
    out.push("");
    out.push(model.reflection.what_to_change || "_Not completed._");
    out.push("");
    out.push("### Recommended controls");
    out.push("");
    const controls = model.reflection.recommended_controls.filter((c) => c.trim());
    if (controls.length === 0) {
      out.push("_None recorded._");
    } else {
      for (const control of controls) out.push(`- ${control}`);
    }
  } else {
    out.push("_The post-incident review was not completed._");
  }
  out.push("");

  out.push("### Model recommendations for comparison");
  out.push("");
  for (const recommendation of model.scenario.model_recommendations) {
    out.push(`- ${recommendation}`);
  }
  out.push("");

  // --------------------------------------------------------------- score --
  out.push("## Score breakdown");
  out.push("");
  out.push(
    table(
      ["Component", "Points"],
      [
        [
          "Decisions",
          `${g.decisions.reduce((s, d) => s + Math.max(0, d.points_earned), 0)} / ${g.decisions.reduce((s, d) => s + d.points_possible, 0)}`,
        ],
        [
          "Response actions",
          `${g.actions.reduce((s, a) => s + Math.max(0, a.points_earned), 0)} / ${g.actions.reduce((s, a) => s + a.points_possible, 0)}`,
        ],
        [
          "Indicators identified",
          String(g.iocs.filter((i) => i.status === "correct").reduce((s, i) => s + i.points, 0)),
        ],
        ["Post-incident review", `${g.reflection.points_earned} / ${g.reflection.points_possible}`],
        ["Hints used", `-${g.hint_penalty}`],
        ["False positives and incorrect actions", `-${g.false_positive_penalty}`],
        ["**Total**", `**${g.score} / ${g.max_score} (${g.percentage}%)**`],
      ],
    ),
  );
  out.push("");

  if (g.badges.length > 0) {
    out.push(`**Badges earned:** ${g.badges.join(", ")}`);
    out.push("");
  }

  if (model.queries.length > 0) {
    out.push("## Queries run");
    out.push("");
    out.push(
      table(
        ["Time (UTC)", "Query", "Results"],
        model.queries.map((q) => [formatUtc(q.at), `\`${q.query}\``, String(q.results)]),
      ),
    );
    out.push("");
  }

  // ------------------------------------------------------ instructor box --
  out.push("## Instructor comments");
  out.push("");
  if (model.instructor_comments.length === 0) {
    out.push("_No comments have been added yet._");
    out.push("");
    out.push("```");
    out.push("");
    out.push("");
    out.push("");
    out.push("```");
  } else {
    for (const comment of model.instructor_comments) {
      out.push(`**${comment.instructor_handle}** (${formatUtc(comment.created_at)}):`);
      out.push("");
      out.push(`> ${comment.comment}`);
      out.push("");
    }
  }
  out.push("");

  out.push("---");
  out.push("");
  out.push(
    `Generated by NocturneAnalysis on ${formatUtc(model.generated_at)} from ${model.event_count} ` +
      `recorded events. Chain head \`${shortHash(model.integrity.headHash)}\`. ` +
      `MITRE ATT&CK(R) is a registered trademark of The MITRE Corporation.`,
  );
  out.push("");

  return out.join("\n");
}
