import type { Metadata } from "next";
import { notFound } from "next/navigation";

import { ReportView } from "@/components/report/report-view";
import { buildSampleReport, listSampleSessions } from "@/lib/content/samples";

export function generateStaticParams() {
  return listSampleSessions().map((s) => ({ slug: s.scenario_slug }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const model = await buildSampleReport(slug);
  if (!model) return { title: "Sample not found" };
  return {
    title: `Sample report: ${model.scenario.title}`,
    description: `A complete incident report produced by NocturneAnalysis, scored ${model.grade.score}/${model.grade.max_score}.`,
  };
}

export default async function SampleReportPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const model = await buildSampleReport(slug);
  if (!model) notFound();

  return (
    <div className="mx-auto w-full max-w-4xl px-4 py-12">
      <p className="mb-6 rounded-md border border-primary/30 bg-primary/5 p-3 text-sm text-muted-foreground">
        This is a demonstration report from a worked example. It was generated by the same pipeline
        that grades a real student submission - the analyst below is fictional, and so is every
        system named in the incident.
      </p>

      <ReportView
        model={model}
        downloads={{
          pdf: `/samples/${slug}/report.pdf`,
          markdown: `/samples/${slug}/report.md`,
        }}
      />
    </div>
  );
}
